"""Application-wide numeric limits."""

MAX_PAGE_SIZE = 100
DEFAULT_PAGE_SIZE = 20
MAX_WORKOUT_DURATION_MINUTES = 600
MAX_SETS_PER_WORKOUT = 100
MAX_JOURNAL_BODY_LENGTH = 10_000
MAX_GOAL_TITLE_LENGTH = 150
